/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Ingressos;

import static javax.swing.JOptionPane.*;
import Control.IngressoPistaControl;

/**
 *
 * @author Note
 */
public class TelaIngressoPista extends javax.swing.JFrame {

    //atributo para CONTROL
    public IngressoPistaControl c;

    /**
     * Creates new form TelaIngressoPista
     */
    public TelaIngressoPista() {
        this.c = new IngressoPistaControl(); //quando a tela for iniciada será tbm instanciado um obj control
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_nome = new javax.swing.JLabel();
        textField_nome = new java.awt.TextField();
        jLabel_idade = new javax.swing.JLabel();
        textField_cpf = new java.awt.TextField();
        jLabel_cpf = new javax.swing.JLabel();
        jLabel_phone = new javax.swing.JLabel();
        textField_phone = new java.awt.TextField();
        textField_idade = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textField1_qtdeIngresso = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();

        setTitle("Compra Ingresso Pista");
        setResizable(false);

        jLabel1.setText("Você está na tela referente ao Ingresso Pista");

        jLabel_nome.setText("Nome:");

        textField_nome.setText("");

        jLabel_idade.setText("Idade:");

        textField_cpf.setText("");
        textField_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_cpfActionPerformed(evt);
            }
        });

        jLabel_cpf.setText("CPF:");

        jLabel_phone.setText("telefone");

        textField_phone.setText("");

        textField_idade.setText("");

        jLabel2.setText("Tipo de Ingresso:");

        jLabel3.setText("Quantidade:");

        textField1_qtdeIngresso.setText("");

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textField_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textField_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(textField1_qtdeIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(201, 201, 201))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel_nome))
                    .addComponent(textField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_idade)
                    .addComponent(textField_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel_cpf))
                    .addComponent(textField_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_phone)
                    .addComponent(textField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(textField1_qtdeIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textField_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_cpfActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {

            String nome;
            long cpf;
            int idade;
            long phone;
            String sexo = "";

            String masc = "Masculino";
            String fem = "Feminino";

            /*pede uma confirmação dos dados
        int confirm = showConfirmDialog(null, "Deseja confirmar a solicitação de compra? \n Dados: \n"
                + "Nome: " + this.textField_nome.getText() + "\n"
                + "Idade: " + this.textField_idade.getText()+ "\n"
                + "CPF: " + this.textField_cpf.getText()+ "\n"
                + "Email: " + this.textField_email.getText()+ "\n"
                + "Sexo: " + this.jComboBox1.getItemAt()+ "\n"
                , "AVISO!", YES_NO_OPTION);
             */
            //faz mais uns if para verificar a confirmação dos dados (se todos foram inseridos,etc...
            if (textField_nome.getText().length() <= 1) {
                showMessageDialog(null, "Preencha corretamente o campo 'Nome' \n"
                        + "(ao menos 2 caracteres é necessário!)");
            } else {
                //adiciona o dado a uma variavel (que dps sera utilizada para o cadastro)
                nome = this.textField_nome.getText();

                if (textField_idade.getText().length() <= 1) { //verifica o tamanho (2 caracteres)
                    showMessageDialog(null, "Idade deve ter no mínimo 2 caracteres! \n"
                            + "(alem de ser maior que 18 obvio kkk)");
                    //fazer uma verificação de idade apos transformar o valor em int
                } else {
                    //adiciona o dado a uma variavel (que dps sera utilizada para o cadastro)
                    idade = Integer.parseInt(this.textField_idade.getText());

                    if (textField_cpf.getText().length() != 11) { //deve conter 11 dígitos exatos
                        showMessageDialog(null, "Preencha o campo 'Cpf' somente com números + \n"
                                + "(11 dígitos)");
                    } else {
                        //adiciona o dado 'cpf' a uma variavel (que dps sera utilizada para o cadastro)
                        cpf = Long.parseLong(this.textField_cpf.getText());

                        //adiciona o dado 'telefone' a uma variavel (que dps sera utilizada para o cadastro)
                        if (this.textField_phone.getText().length() != 11) {
                            showMessageDialog(null, "Preencha o campo Telefone com DDD + 9 dígitos");
                        } else {
                            phone = Long.parseLong(this.textField_phone.getText());

                            if (jComboBox2.getSelectedItem().equals(masc)) {
                                sexo = "Masculino";
                            } else if (jComboBox2.getSelectedItem().equals(fem)) {
                                sexo = "Feminino";
                            }

                            /* adiciona o dado 'qtde. ingressos' a uma variavel (que dps sera utilizada para o cadastro) 
             serve para registrar a quantidade de ingressos em si, além de somar no valor final do pedido */
                            if (this.textField1_qtdeIngresso.getText().equalsIgnoreCase("")) {
                                showMessageDialog(null, "Por favor, digite a quantidade de ingressos que deseja comprar");
                            } else {
                                int qtdIngresso = Integer.parseInt(this.textField1_qtdeIngresso.getText());
                                double valorSexo = 0;

                                if (sexo.equalsIgnoreCase("Masculino")) {
                                    valorSexo = 70;
                                } else if (sexo.equalsIgnoreCase("Feminino")) {
                                    valorSexo = 60;
                                }

                                double valor = qtdIngresso * valorSexo;

                                //informa o valor total da compra e faz mais uma confirmação
                                int confirm2 = showConfirmDialog(null, "Deseja confirmar a compra?" + "\n"
                                        + "Valor: R$" + valor,
                                        "AVISO!", YES_NO_OPTION);

                                //realiza a compra e efetua o cadastro no bd
                                if (confirm2 == YES_OPTION) {

                                    if (idade < 18) {
                                        showMessageDialog(null, "Você deve ter mais de 18 anos para ir ao evento!");
                                    } else if (c.cadastrarIngressoPista(nome, idade, cpf, phone, sexo) == true) {
                                        showMessageDialog(null, "Compra efetuada com sucesso! \n Te esperamos no evento!");
                                        System.out.println(c.getMinhaLista().toString());

                                        this.textField_nome.setText("");
                                        this.textField_idade.setText("");
                                        this.textField_cpf.setText("");
                                        this.textField_phone.setText("");
                                        this.textField1_qtdeIngresso.setText("");
                                        this.jComboBox2.removeAllItems();
                                        this.jComboBox2.addItem("Masculino");
                                        this.jComboBox2.addItem("Feminino");

                                    } else {
                                        showMessageDialog(null, "ERRO! \n Verifique os dados e tente novamente!");
                                    }

                                }

                            }
                        }
                    }
                }
            }

            // se clicar em "Não" foda-se, nao precisa fazer nada (e não irá fazer, pois os dados só são enviados se clicar em "Sim")
        } catch (NumberFormatException a) {
            showMessageDialog(null, "Por favor, verifique se você inseriu somente números nos campos: \n"
                    + "   CPF, TELEFONE, QUANTIDADE");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaIngressoPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaIngressoPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaIngressoPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaIngressoPista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaIngressoPista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_cpf;
    private javax.swing.JLabel jLabel_idade;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_phone;
    private java.awt.TextField textField1_qtdeIngresso;
    private java.awt.TextField textField_cpf;
    private java.awt.TextField textField_idade;
    private java.awt.TextField textField_nome;
    private java.awt.TextField textField_phone;
    // End of variables declaration//GEN-END:variables
}
